# Generated by Django 2.1.5 on 2019-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('track_name', models.TextField()),
                ('n_citacoes', models.IntegerField()),
                ('size_bytes', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('prime_genre', models.CharField(max_length=150)),
            ],
        ),
    ]
